alias csj="cd Documents/CS/Java"
alias vim="$EDITOR"
alias v=$EDITOR 
alias vold="/usr/bin/vim"
alias vimrc="$EDITOR ~/.config/nvim/init.vim"
alias voldrc="vold ~/.vimrc"
alias i3conf="$EDITOR ~/.config/i3/config"
alias bashrc="$EDITOR ~/.bashrc"
alias mutt=neomutt
alias muttrc="$EDITOR ~/.config/mutt/muttrc"
alias pac='sudo pacman -Syu'
alias rmc="rm *.class"
alias ytd="youtube-dl -x --audio-format mp3"
alias rmswp="rm ~/.cache/vim/swap/*;rm ~/.local/share/nvim/swap/*"
alias search="fzf | xargs -r $EDITOR"
