alias csj="cd Documents/CS/Java"
alias v=vim #Not used often
alias pac='sudo pacman -Syu'
alias vimrc="vim ~/.vimrc"
alias i3conf="vim ~/.config/i3/config"
alias bashrc="vim ~/.bashrc"
alias mutt=neomutt
alias muttrc="vim ~/.config/mutt/muttrc"
alias rmc="rm *.class"
alias ytd="youtube-dl -x --audio-format mp3"
alias ytpd="youtube-dl --yes-playlist -x --audio-format mp3"
