alias csj="cd Documents/CS/Java"
alias v=vim
alias pac='sudo pacman -Syu'
alias vimrc="vim ~/.vimrc"
alias i3conf="vim ~/.config/i3/config"
alias bashrc="vim ~/.bashrc"
alias mail="neomutt"
alias mutt=neomutt
alias muttrc="vim ~/.config/mutt/muttrc"
